### ISSUE TITLE
Avoid the need of adding cyclonedx-maven-plugin

### ISSUE THREAD

**Issue by manolo** [vaadin/appsec-kit#110] opened 2023-10-17 09:29 UTC
Since `vaadin-dev-server` has already a set of `Updaters` that are run when source or dependencies are modified, it should be possible to register other updaters like the SBOM generator, just when the dependency is added.

Another option is make `vaadin-maven-plugin` in the `prepare-frontend` goal check dependencies and see where there is some external actions that should be performed.

**Comment by heruan** [comment] 2023-11-23 07:53
Closed as duplicate of #14

**Closed by heruan** 2023-11-23 07:53 UTC
Labels: enhancement
